import "./globals.css";
import HomePage from "./pages/HomePage/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HomePage />
      {/* <body>{children}</body> */}
    </html>
  );
}
